name: Deploy Bot to Server

on:
  push:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
  push:
    branches:
      - main
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run the bot
        run: |
          python bot.py
